#! /bin/bash

read -pr "Download video portion? (Y/N): " video && \
    [[ $video == [yY] || $video == [yY][eE][sS] ]] || exit 1

echo "[ytdl] Updating Termux package indexes...";
pkg update -y;
echo "[ytdl] Installing Termux packages...";
pkg install -y ffmpeg python;

echo "[ytdl] Updating pip and setuptools...";
pip install --user --upgrade pip setuptools;
echo "[ytdl] Updating PLACEHOLDERNAME...";
pip install --user --upgrade PLACEHOLDERNAME;

echo "[ytdl] Running PLACEHOLDERNAME...";
dlfolder="/data/data/com.termux/files/home/storage/downloads"
if $video; then
    # Video and audio
    /data/data/com.termux/files/home/.local/bin/PLACEHOLDERNAME \
         -f "best[height<=480] \
        -o "$dlfolder/Youtube/Videos/%(title)s.%(ext)s" "$1" \
    ;
else
    # Audio-only
    /data/data/com.termux/files/home/.local/bin/PLACEHOLDERNAME \
        --extract-audio --audio-format mp3 --audio-quality 3 \
        --prefer-ffmpeg --postprocessor-args "-id3v2_version 3" \
        -o "$dlfolder/Youtube/Songs/%(title)s.%(ext)s" "$1" \
    ;
fi
