#! /bin/bash

url="$1"  # Must be before bash's read command
read -p 'Download video portion? (y/n): ' -r video

echo "[ytdl] Updating Termux package indexes...";
pkg update -y;
echo "[ytdl] Installing Termux packages...";
pkg install --no-install-recommends -y ffmpeg python;

echo "[ytdl] Installing latest versions of pip and setuptools...";
pip install --user --upgrade pip setuptools;
echo "[ytdl] Updating PLACEHOLDERNAME...";
pip install --user --upgrade PLACEHOLDERNAME;

echo "[ytdl] Creating ytdl config directory if it does not already exist...";
mkdir -p "$HOME/.config/ytdl/";
ycfgpath="$HOME/.config/ytdl/ytdl-config";
if [[ -f "$ycfgpath" ]]; then
    echo "[ytdl] Found the local ytdl-config, so not retrieving remote one.";
else
    echo "[ytdl] Retrieving ytdl config script...";
    ytdlcfgurl="https://raw.githubusercontent.com/nth10sd";
    ytdlcfgurl+="/ytdl/master/cfg/ytdl-config";
    curl --proto '=https' --tlsv1.2 -sSf \
        -o "$ycfgpath" "$ytdlcfgurl";
fi

echo "[ytdl] Creating $1 config directory if it does not already exist...";
mkdir -p "$HOME/.config/$1/";
echo "[ytdl] Retrieving $1 config script...";
configurl="https://raw.githubusercontent.com/nth10sd/ytdl/master/cfg/config";
curl --proto '=https' --tlsv1.2 -sSf -o "$HOME/.config/$1/config" "$configurl";

echo "[ytdl] Parsing ytdl-config...";
IFS="=";
while read -r variable value; do
if [[ $variable == audioquality ]]; then
    echo "[ytdl] $variable value from config file is: ${value//\"/}";
    audioquality="${value//\"/}";
    echo "[ytdl] Audio quality used will be: $audioquality";
elif [[ $variable == dlfolder ]]; then
    echo "[ytdl] $variable value from config file is: ${value//\"/}";
    dlfolder="${value//\"/}";
    echo "[ytdl] Files will be saved in: $dlfolder";
elif [[ $variable == maxvideoquality ]]; then
    echo "[ytdl] $variable value from config file is: ${value//\"/}";
    maxvideoquality="${value//\"/}";
    echo "[ytdl] Audio quality used will be: $maxvideoquality";
fi
done < "$ycfgpath";

echo "[ytdl] Running PLACEHOLDERNAME...";
if [[ "$video" == [yY] || "$video" == [yY][eE][sS] ]]; then
    echo "Creating destination directory...";
    mkdir -p "$HOME/storage/downloads/VideosObtained/";
    echo "Downloading both portions as preference was: $video";
    vidpath="$dlfolder/VideosObtained";
    vidpath+="/%(title)s-maxVq$maxvideoquality-Aq$audioquality.%(ext)s";
    /data/data/com.termux/files/home/.local/bin/PLACEHOLDERNAME \
        -f "best[height<=$maxvideoquality]" \
        -o "$vidpath" "$url" \
    ;
else
    echo "Creating destination directory...";
    mkdir -p "$HOME/storage/downloads/SongsObtained/";
    echo "Downloading audio-only...";
    songpath="$dlfolder/SongsObtained/%(title)s-Aq$audioquality.%(ext)s";
    /data/data/com.termux/files/home/.local/bin/PLACEHOLDERNAME \
        --extract-audio --audio-format mp3 --audio-quality "$audioquality" \
        --prefer-ffmpeg --postprocessor-args "-id3v2_version 3" \
        -o "$songpath" "$url" \
    ;
fi
